"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Layers, CheckCircle, Loader2, Clock, Code, FileCode } from "lucide-react"
import { GENERATION_SYSTEMS } from "@/lib/engine/config"

const sampleCode = `// Generated by NEXUS-116 Agent Fleet
// System: Combat | Engine: Unreal 5 | Optimized

#pragma once
#include "CoreMinimal.h"
#include "GameplayAbilitySpec.h"
#include "NexusCombatSystem.generated.h"

USTRUCT(BlueprintType)
struct FDamageEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float BaseDamage = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    EDamageType DamageType = EDamageType::Physical;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    AActor* Instigator = nullptr;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FHitResult HitResult;

    // Damage pipeline: base -> type mult -> armor -> resist -> final
    float CalculateFinalDamage(const UCombatComponent* Target) const;
};

UCLASS(ClassGroup=(Combat), meta=(BlueprintSpawnableComponent))
class NEXUS116_API UCombatComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UCombatComponent();

    // --- Damage Pipeline ---
    UFUNCTION(BlueprintCallable, Category = "Combat")
    float ApplyDamage(const FDamageEvent& Event);

    UFUNCTION(Server, Reliable)
    void ServerApplyDamage(const FDamageEvent& Event);

    // --- Stats ---
    UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
    float MaxHealth = 100.f;

    UPROPERTY(ReplicatedUsing=OnRep_CurrentHealth)
    float CurrentHealth = 100.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float ArmorRating = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TMap<EDamageType, float> Resistances;

    // --- Hit Detection ---
    UFUNCTION(BlueprintCallable, Category = "Combat")
    TArray<FHitResult> MeleeTrace(float Range, float Arc);

    UFUNCTION(BlueprintCallable, Category = "Combat")
    FHitResult HitscanTrace(float Range);

protected:
    UFUNCTION()
    void OnRep_CurrentHealth();

    virtual void GetLifetimeReplicatedProps(
        TArray<FLifetimeProperty>& OutLifetimeProps) const override;
};`

export function GenerationPanel() {
  const totalLines = GENERATION_SYSTEMS.reduce((s, sys) => s + sys.linesGenerated, 0)
  const completed = GENERATION_SYSTEMS.filter(s => s.status === "complete").length

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <Card className="border-border/50 bg-card/50 p-4">
          <p className="text-xs text-muted-foreground">Systems Generated</p>
          <p className="text-2xl font-mono font-bold text-emerald-400">{completed}/{GENERATION_SYSTEMS.length}</p>
        </Card>
        <Card className="border-border/50 bg-card/50 p-4">
          <p className="text-xs text-muted-foreground">Total Lines</p>
          <p className="text-2xl font-mono font-bold">{totalLines.toLocaleString()}</p>
        </Card>
        <Card className="border-border/50 bg-card/50 p-4">
          <p className="text-xs text-muted-foreground">Target Engine</p>
          <p className="text-lg font-mono font-bold">Unreal 5</p>
        </Card>
        <Card className="border-border/50 bg-card/50 p-4">
          <p className="text-xs text-muted-foreground">Optimization</p>
          <p className="text-lg font-mono font-bold">Production</p>
        </Card>
      </div>

      {/* Systems Grid */}
      <Card className="border-border/50 bg-card/50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Layers className="h-5 w-5" />
            Game Systems Pipeline
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
            {GENERATION_SYSTEMS.map((sys) => (
              <div key={sys.name} className={`rounded-lg border p-4 ${
                sys.status === "generating" ? "border-amber-500/30 bg-amber-500/5" :
                sys.status === "optimizing" ? "border-purple-500/30 bg-purple-500/5" :
                sys.status === "complete" ? "border-emerald-500/20" :
                "border-border/50"
              }`}>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {sys.status === "complete" && <CheckCircle className="h-4 w-4 text-emerald-400" />}
                    {sys.status === "generating" && <Loader2 className="h-4 w-4 text-amber-400 animate-spin" />}
                    {sys.status === "optimizing" && <Loader2 className="h-4 w-4 text-purple-400 animate-spin" />}
                    {sys.status === "pending" && <Clock className="h-4 w-4 text-muted-foreground" />}
                    <span className="font-medium">{sys.displayName}</span>
                  </div>
                  <Badge variant="outline" className={`text-[10px] font-mono ${
                    sys.status === "complete" ? "border-emerald-500/30 text-emerald-400" :
                    sys.status === "generating" ? "border-amber-500/30 text-amber-400" :
                    sys.status === "optimizing" ? "border-purple-500/30 text-purple-400" :
                    ""
                  }`}>
                    {sys.status}
                  </Badge>
                </div>
                {sys.linesGenerated > 0 && (
                  <div className="flex items-center gap-2 mt-2">
                    <FileCode className="h-3 w-3 text-muted-foreground" />
                    <span className="text-xs text-muted-foreground font-mono">{sys.linesGenerated.toLocaleString()} lines C++</span>
                  </div>
                )}
                {sys.status !== "pending" && (
                  <Progress
                    value={sys.status === "complete" ? 100 : sys.status === "optimizing" ? 80 : 50}
                    className="h-1 mt-2"
                  />
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Code Preview */}
      <Card className="border-border/50 bg-card/50">
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Code className="h-4 w-4" />
            Generated Code Preview &mdash; Combat System
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ScrollArea className="h-[400px]">
            <pre className="text-xs font-mono text-emerald-400/80 leading-relaxed bg-black/30 rounded-lg p-4">
              {sampleCode}
            </pre>
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  )
}
